Repository open-dollar/od-app, pull requests merged in 2023-07, with the labels that each got.

#12 Devlink (new PR)
  .eslintignore
  .gitignore
  README.md
  craco.config.js
  package.json
  src/App.tsx
  src/containers/Splash.tsx
  src/devlink/TestComponent.d.ts
  src/devlink/TestComponent.js
  src/devlink/TestComponent.module.css
  src/devlink/_Builtin/BackgroundVideo.d.ts
  src/devlink/_Builtin/BackgroundVideo.js
  src/devlink/_Builtin/Basic.d.ts
  src/devlink/_Builtin/Basic.js
  src/devlink/_Builtin/Dropdown.d.ts
  src/devlink/_Builtin/Dropdown.js
  src/devlink/_Builtin/Facebook.d.ts
  src/devlink/_Builtin/Facebook.js
  src/devlink/_Builtin/Form.d.ts
  src/devlink/_Builtin/Form.js
  src/devlink/_Builtin/Map.d.ts
  src/devlink/_Builtin/Map.js
  src/devlink/_Builtin/Navbar.d.ts
  src/devlink/_Builtin/Navbar.js
  src/devlink/_Builtin/Slider.d.ts
  src/devlink/_Builtin/Slider.js
  src/devlink/_Builtin/Tabs.d.ts
  src/devlink/_Builtin/Tabs.js
  src/devlink/_Builtin/Twitter.d.ts
  src/devlink/_Builtin/Twitter.js
  src/devlink/_Builtin/Typography.d.ts
  src/devlink/_Builtin/Typography.js
  src/devlink/_Builtin/Video.d.ts
  src/devlink/_Builtin/Video.js
  src/devlink/_Builtin/YouTubeVideo.d.ts
  src/devlink/_Builtin/YouTubeVideo.js
  src/devlink/_Builtin/index.d.ts
  src/devlink/_Builtin/index.js
  src/devlink/devlink.d.ts
  src/devlink/devlink.js
  src/devlink/devlinkContext.d.ts
  src/devlink/devlinkContext.js
  src/devlink/global.css
  src/devlink/index.d.ts
  src/devlink/index.js
  src/devlink/interactions.d.ts
  src/devlink/interactions.js
  src/devlink/types.d.ts
  src/devlink/types.js
  src/devlink/utils.d.ts
  src/devlink/utils.js
  src/hooks/useContract.ts
  yarn.lock
Labels: web, dependency change, size/XXL

#16 Issue #7: Display amount dollar value
  src/containers/Safes/CreateSafe.tsx
Labels: web

#26 Change HAI to OD
  src/components/Brand.tsx
  src/components/Navbar.tsx
  src/components/SafeStats.tsx
  src/containers/Safes/CreateSafe.tsx
  src/containers/Safes/ModifySafe.tsx
  src/containers/Splash.tsx
  src/hooks/useGeb.ts
  src/hooks/useSafe.ts
  src/model/safeModel.ts
  src/services/safes.ts
  src/utils/constants.ts
  src/utils/helper.ts
  src/utils/i18n/en.json
  src/utils/tokens.ts
Labels: web

#30 Page routing and stats
  package.json
  src/App.tsx
  src/containers/Safes/Stats.js
  src/containers/Safes/index.tsx
  src/hooks/useStats.js
  src/utils/graph.js
  src/utils/helpers.js
  src/utils/queries.js
  yarn.lock
Labels: web, dependency change, size/XL

#36 Issue #35: Fix disappeared header
  src/containers/Safes/Stats.js
  src/containers/Safes/index.tsx
  src/containers/Shared.tsx
  src/hooks/useStats.js
  src/utils/graph.js
  src/utils/helpers.js
  src/utils/queries.js
Labels: web

#34 Change HAI to OD (update)
  README.md
  public/icon.png
  public/index.html
Labels: web, dependency change, size/S

#37 Stats styling
  src/assets/Mark.svg
  src/components/Icons/OdLoadingIcon.tsx
  src/components/Loader.tsx
  src/containers/Safes/Stats.js
Labels: web, size/L
