Repository open-dollar/od-app, pull requests merged in 2023-08, with the labels that each got.

#27 Styling changes
  cypress/integration/landing-no-safes.test.ts
  cypress/integration/landing-safes.test.ts
  cypress/integration/safe-details.test.ts
  src/App.tsx
  src/GlobalStyle.tsx
  src/assets/od-full-logo.png
  src/assets/od-full-logo.svg
  src/assets/od-logo.svg
  src/components/Brand.tsx
  src/components/CheckBox.tsx
  src/components/LinkButton.tsx
  src/components/Modals/SafeManagerModal.tsx
  src/components/Modals/WETHModal.tsx
  src/components/NavLinks.tsx
  src/components/Navbar.tsx
  src/components/Steps.tsx
  src/components/VaultBlock.tsx
  src/components/VaultManager.tsx
  src/components/VaultStats.tsx
  src/containers/Auctions/AuctionsList.tsx
  src/containers/Auctions/CollateralAuctions/CollateralAuctionsList.tsx
  src/containers/Shared.tsx
  src/containers/Splash.tsx
  src/containers/Vaults/Accounts.tsx
  src/containers/Vaults/CreateVault.tsx
  src/containers/Vaults/ModifyVault.tsx
  src/containers/Vaults/Review.tsx
  src/containers/Vaults/Stats.js
  src/containers/Vaults/VaultDetails.tsx
  src/containers/Vaults/VaultHeader.tsx
  src/containers/Vaults/VaultList.tsx
  src/containers/Vaults/index.tsx
  src/containers/Vaults/wrapEth/Results.tsx
  src/containers/Vaults/wrapEth/TxConfirmation.tsx
  src/containers/Vaults/wrapEth/Wrap.tsx
  src/containers/Vaults/wrapEth/index.tsx
  src/devlink/global.css
  src/model/safeModel.test.ts
  src/model/safeModel.ts
  src/utils/i18n/en.json
  src/utils/themes/dark.ts
  src/utils/themes/light.ts
  src/utils/tokens.ts
Labels: web, size/XL

#40 Issue #32: Confirm Transaction Details
  src/assets/hai-logo.svg
  src/assets/od-logo.png
  src/components/Icons/OdLoadingIcon.tsx
  src/components/Icons/TransactionSpinner.tsx
  src/components/Loader.tsx
  src/components/TransactionOverview.tsx
  tailwind.config.js
Labels: web

#41 Issue #2: Switch network improvement
  src/components/WalletModal/index.tsx
Labels: web

#52 Issue #47: Wrap eth link updated
  src/containers/Vaults/CreateVault.tsx
Labels: web

#54 Issue #46: Awaiting tx modal missing
  src/containers/Shared.tsx
Labels: web, size/XS

#51 Issue #44: Reorder components on index page
  src/containers/Vaults/index.tsx
Labels: web

#56 Issue #48: QA Vault details
  src/components/VaultStats.tsx
Labels: web, size/L

#53 QA - links, modals, commas
  package.json
  src/components/ConnectedWalletInfo.tsx
  src/components/TokenInput.tsx
  src/components/VaultBlock.tsx
  src/components/VaultStats.tsx
  src/containers/Vaults/CreateVault.tsx
  src/containers/Vaults/ModifyVault.tsx
  src/containers/Vaults/Stats.js
  src/containers/Vaults/index.tsx
  src/model/safeModel.ts
  src/utils/helper.ts
  yarn.lock
Labels: web, dependency change, size/L

#55 Create vault copy
  src/utils/i18n/en.json
Labels: web, dependency change, size/XS

#63 Menu bar update
  package.json
  src/App.tsx
  src/components/Icons/ArrowDown.tsx
  src/components/Icons/LoadingDots.tsx
  src/components/Icons/Uniswap.tsx
  src/components/NavLinks.tsx
  src/components/Navbar.tsx
  src/utils/i18n/de.json
  src/utils/i18n/en.json
  yarn.lock
Labels: web, dependency change, size/L

#64 Stats page
  src/assets/eth-icon.svg
  src/assets/nfts-icon.svg
  src/containers/Analytics/DataCard.tsx
  src/containers/Analytics/index.tsx
Labels: web, dependency change

#66 Update tables
  src/components/CustomTooltip.tsx
  src/components/Icons/CopyIcon.tsx
  src/components/Icons/CopyIconBlue.tsx
  src/containers/Analytics/ContractsTable.tsx
  src/containers/Analytics/DataTable.tsx
  src/containers/Analytics/index.tsx
Labels: web

#72 Make header responsive
  src/components/NavLinks.tsx
  src/components/Navbar.tsx
Labels: web

#73 Update react tooltip
  package.json
  solidity/cache/solidity-files-cache.json
  src/components/Modals/ProxyModal.tsx
  src/components/Steps.tsx
  src/components/VaultBlock.tsx
  src/components/VaultStats.tsx
  src/containers/Analytics/ContractsTable.tsx
  src/containers/Analytics/DataCard.tsx
  src/containers/Analytics/DataTable.tsx
  src/containers/Analytics/index.tsx
  src/containers/Vaults/CreateVault.tsx
  src/containers/Vaults/Review.tsx
  yarn.lock
Labels: web, dependency change, size/L

#91 Issue #90: QA cleanup - disconnect from modal, double copy button
  src/components/ConnectedWalletInfo.tsx
  src/components/Icons/CopyIcon.tsx
  src/connectors/coinbaseWallet.ts
Labels: web, dependency change, size/S

#94 Data fetching errors
  src/containers/Shared.tsx
  src/containers/Vaults/index.tsx
Labels: web, size/XS

#95 QA - Stats page
  src/components/VaultStats.tsx
  src/containers/Analytics/ContractsTable.tsx
  src/containers/Analytics/index.tsx
  src/containers/Vaults/VaultHeader.tsx
  src/utils/contractsDescription.ts
  src/utils/formatDataNumber.ts
  src/utils/helper.ts
  src/utils/misc.ts
Labels: web

#98 Issue #81: QA - Wallet connect modal styling
  src/components/connectorCards/Card.tsx
  src/components/connectorCards/Status.tsx
Labels: web

#97 Issue #80: QA - Add RPC to always show stats
  src/components/Web3ReactManager/index.tsx
Labels: web

#96 Issue #89: QA - Network selection
  src/App.tsx
  src/components/ToastPayload.tsx
  src/components/WalletModal/index.tsx
  src/components/connectorCards/CoinbaseWalletCard.tsx
  src/components/connectorCards/MetaMaskCard.tsx
  src/components/connectorCards/WalletConnectCard.tsx
  src/components/connectorCards/WalletConnectV2Card.tsx
  src/containers/Shared.tsx
  src/model/connectWalletModel.ts
  src/utils/constants.ts
  src/utils/helper.ts
Labels: web
