Repository open-dollar/od-app, pull requests merged in 2024-06, with the labels that each got.

#554 Issue #409: Reduce redundant RPC calls
  src/components/AuctionsOperations/AuctionsTransactions.tsx
  src/components/Navbar.tsx
  src/components/SideMenu.tsx
  src/components/Steps.tsx
  src/components/VaultStats.tsx
  src/components/WalletModal/index.tsx
  src/containers/Analytics/index.tsx
  src/containers/Earn/EarnDetails.tsx
  src/containers/Earn/index.tsx
  src/containers/Shared.tsx
  src/containers/Vaults/CreateVault.tsx
  src/containers/Vaults/ModifyVault.tsx
  src/containers/Vaults/Stats.js
  src/containers/Vaults/wrapEth/TxConfirmation.tsx
  src/hooks/usePoolData.ts
  src/model/auctionModel.ts
  src/model/index.ts
  src/model/nitroPoolsModel.ts
  src/model/poolDataModel.ts
  src/model/safeModel.ts
  src/services/blockchain.ts
  src/utils/auctions.ts
  src/utils/wrapEther.ts
Labels: web, size/XL

#558 Issue #463. QA: Vault modification new "After" text
  src/components/VaultStats.tsx
Labels: web, ch-37

#563 Release- bug fixes, Marketplace POC
  package.json
  public/index.html
  src/GlobalStyle.tsx
  src/components/AuctionsOperations/AuctionsTransactions.tsx
  src/components/Navbar.tsx
  src/components/SideMenu.tsx
  src/components/Steps.tsx
  src/components/ToastBannerNetwork.tsx
  src/components/VaultStats.tsx
  src/components/WalletModal/index.tsx
  src/containers/Analytics/index.tsx
  src/containers/Auctions/CollateralAuctions/CollateralAuctionBlock.tsx
  src/containers/Bolts/Affiliate.tsx
  src/containers/Bolts/QuestBlock.tsx
  src/containers/Bolts/index.tsx
  src/containers/Bolts/quests.tsx
  src/containers/Earn/EarnDetails.tsx
  src/containers/Earn/index.tsx
  src/containers/Marketplace/Table.tsx
  src/containers/Marketplace/index.css
  src/containers/Marketplace/index.tsx
  src/containers/Shared.tsx
  src/containers/Vaults/CreateVault.tsx
  src/containers/Vaults/ModifyVault.tsx
  src/containers/Vaults/Stats.js
  src/containers/Vaults/VaultDetails.tsx
  src/containers/Vaults/wrapEth/TxConfirmation.tsx
  src/hooks/useAnalyticsData.ts
  src/hooks/useOpenSeaListings.ts
  src/hooks/usePoolData.ts
  src/hooks/useVaultSubgraph.ts
  src/model/analyticsModel.ts
  src/model/auctionModel.ts
  src/model/index.ts
  src/model/nitroPoolsModel.ts
  src/model/poolDataModel.ts
  src/model/safeModel.ts
  src/services/blockchain.ts
  src/services/opensea.ts
  src/utils/auctions.ts
  src/utils/datesAndTimes.ts
  src/utils/interfaces.ts
  src/utils/wrapEther.ts
  yarn.lock
Labels: web, dependency change, size/XXL

#553 Issue # 547 QA Bridge page
  src/assets/arb.svg
  src/assets/arbitrum.svg
  src/assets/base.svg
  src/assets/eth.svg
  src/assets/ethereum.svg
  src/assets/optimism.svg
  src/assets/polygon.svg
  src/assets/rETH.svg
  src/containers/Bridge/BridgeFundsForm.tsx
  src/containers/Vaults/CreateVault.tsx
  src/containers/Vaults/ModifyVault.tsx
  src/model/bridgeModel.ts
  src/utils/chains.ts
  src/utils/tokens.ts
Labels: web, ch-36, size/XL

#326 Feature/bridge
  public/index.html
  src/App.tsx
  src/assets/arb.svg
  src/assets/arbitrum.svg
  src/assets/base.svg
  src/assets/eth.svg
  src/assets/ethereum.svg
  src/assets/optimism.svg
  src/assets/polygon.svg
  src/assets/rETH.svg
  src/components/Modals/BridgeModal.tsx
  src/components/Modals/LowGasModal.tsx
  src/components/NavLinks.tsx
  src/components/Steps.tsx
  src/containers/Bridge/BridgeFundsForm.tsx
  src/containers/Bridge/index.tsx
  src/containers/Shared.tsx
  src/containers/Vaults/CreateVault.tsx
  src/containers/Vaults/ModifyVault.tsx
  src/model/bridgeModel.ts
  src/model/index.ts
  src/model/popupsModel.ts
  src/utils/chains.ts
  src/utils/formatBridgeUrl.ts
  src/utils/i18n/en.json
  src/utils/interfaces.ts
  src/utils/tokens.ts
Labels: web, size/XXL

#566 Issue #564: Vault creation- small deposit warning
  src/containers/Vaults/CreateVault.tsx
  src/containers/Vaults/ModifyVault.tsx
  src/hooks/useCollateralBalances.ts
  src/utils/tokens.ts
Labels: web, size/S

#569 Add buffer to max button in create/modify vault
  src/hooks/useSafe.ts
  src/utils/helper.ts
Labels: web, size/M

#571 NFV corner radius #525
  src/components/VaultStats.tsx
  src/containers/Vaults/ModifyVault.tsx
  src/containers/Vaults/VaultHeader.tsx
Labels: web, size/S, ch-37

#565 Issue # 532 Bolts: token logos to be React components w/dynamic widths and heights
  src/assets/od-token.svg
  src/assets/odg-token.svg
  src/components/TokenIcon.tsx
  src/containers/Bolts/quests.tsx
  src/utils/tokens.ts
Labels: web, size/M, ch-37

#570 Issue #535: Bolts Leaderboard
  src/assets/leaderboard-leaders-badge.svg
  src/assets/leaderboard-pillars.svg
  src/containers/Bolts/Leaderboard.tsx
  src/containers/Bolts/index.tsx
  src/containers/Bolts/leaderboard.css
  src/utils/helper.ts
Labels: web, size/L

#567 Issue #534 Bolts: mobile cleanup #2
  src/assets/od-token.svg
  src/components/Navbar.tsx
  src/components/SideMenu.tsx
  src/containers/Bolts/QuestBlock.tsx
  src/containers/Bolts/index.tsx
  src/containers/Bolts/quests.tsx
Labels: web, size/L, ch-37

#573 Issue #508: Bug: View as another wallet
  src/components/VaultManager.tsx
  src/containers/Vaults/VaultDetails.tsx
  src/model/safeModel.ts
Labels: web, size/S

#576 Remove unused images
  src/assets/arbitrum.svg
  src/assets/blueish-bg.webp
  src/assets/boxes.svg
  src/assets/check.svg
  src/assets/close-icon.svg
  src/assets/collateral.svg
  src/assets/curve.svg
  src/assets/debt.svg
  src/assets/error.svg
  src/assets/eth-icon.svg
  src/assets/eth-img.svg
  src/assets/facilitator.webp
  src/assets/flx-logo.svg
  src/assets/flx_uni_eth.svg
  src/assets/flx_uni_hai.svg
  src/assets/footer-bg-art.svg
  src/assets/greenish-bg.webp
  src/assets/incentive.svg
  src/assets/nfts-icon.svg
  src/assets/od-full-logo.webp
  src/assets/od-logo.webp
  src/assets/od-logo192w.webp
  src/assets/od-logo256w.webp
  src/assets/odg.svg
  src/assets/plus.svg
  src/assets/siren.svg
  src/assets/staking.svg
  src/assets/surplus.svg
  src/components/ImagePreloader.tsx
Labels: web, size/XXL, ch-37

#575 Issue 551. QA: Mobile side menu
  src/components/DollarValueInner.tsx
  src/components/NavLinks.tsx
  src/components/Navbar.tsx
  src/components/SideMenu.tsx
  src/components/StepsContent.tsx
Labels: web, size/L

#515 Issue #497. NFV owner bug.
  src/components/VaultStats.tsx
  src/containers/Vaults/VaultDetails.tsx
  src/hooks/useSafe.ts
  src/model/safeModel.test.ts
  src/utils/interfaces.ts
Labels: web, size/M, ch-37

#572 Issue #562: Bolts: Display per-quest points
  src/containers/Bolts/Leaderboard.tsx
  src/containers/Bolts/QuestBlock.tsx
  src/containers/Bolts/index.tsx
  src/containers/Bolts/quests.tsx
  src/hooks/useFuulSDK.ts
Labels: web, size/L

#579 Issue #512: ENS for addresses
  .example.env
  public/index.html
  src/chains.ts
  src/components/AddressLink.tsx
  src/components/BidLine.tsx
  src/components/ConnectedWalletInfo.tsx
  src/components/Navbar.tsx
  src/components/SideMenu.tsx
  src/components/VaultStats.tsx
  src/containers/Bolts/Leaderboard.tsx
  src/hooks/useAddress.ts
  src/utils/tokens.ts
Labels: web, size/L

#586 Staging cleanup 06/20/24
  public/index.html
  src/chains.ts
  src/containers/Bridge/BridgeFundsForm.tsx
Labels: web, size/S

#590 Issue #580: QA release: Bolts
  package.json
  src/components/AddressLink.tsx
  src/components/Bolts/AddressCell.tsx
  src/containers/Bolts/Leaderboard.tsx
  src/containers/Bolts/index.tsx
  src/hooks/useAddress.ts
  src/model/boltsModel.ts
  src/model/index.ts
  yarn.lock
Labels: web, dependency change, size/L

#583 Add deposit, withdraw, and borrow to Matomo analytics
  src/containers/Vaults/CreateVault.tsx
  src/containers/Vaults/ModifyVault.tsx
  src/model/safeModel.ts
  src/react-app-env.d.ts
Labels: web, dependency change, size/M

#592 Issue #589: QA: create vault
  src/containers/Vaults/CreateVault.tsx
Labels: web, size/XS

#594 Fix vault details not rendering when user has multiple vaults
  src/model/safeModel.ts
Labels: web, size/XS

#598 Issue #593: Matomo e-commerce integration
  src/containers/Vaults/CreateVault.tsx
  src/containers/Vaults/ModifyVault.tsx
  src/model/safeModel.ts
Labels: web, size/M
