Repository open-dollar/od-app, pull requests merged in 2024-03, with the labels that each got.

#272 Issue #247: Restrict Leading Zeros in TokenInput
  src/components/TokenInput.tsx
Labels: web

#270 Issue #269: Gnosis Safe Chain ID Issues
  src/components/ConnectWithSelect.tsx
  src/containers/Shared.tsx
  src/utils/i18n/en.json
Labels: web, size/S

#283 Issue #277 #278: Add Themes for New Design
  src/App.tsx
  src/model/settingsModel.ts
  src/utils/interfaces.ts
  src/utils/themes/dark.ts
  src/utils/themes/light.ts
  src/utils/themes/shared.ts
Labels: web, size/L

#284 Issue #306: Fix and Enforce Formatting
  .github/workflows/ci-pr.yml
  package.json
  src/components/AccountCardsWeb3ReactV2.tsx
  src/components/ConnectWithSelect.tsx
  src/components/ConnectedWalletInfo.tsx
  src/components/CookieBanner.tsx
  src/components/CustomTooltip.tsx
  src/components/Footer.tsx
  src/components/Navbar.tsx
  src/components/Pagination.tsx
  src/components/SideMenu.tsx
  src/components/VaultStats.tsx
  src/components/WalletModal/index.tsx
  src/components/Web3ReactManager/index.tsx
  src/components/connectorCards/Card.tsx
  src/components/connectorCards/GnosisCard.tsx
  src/components/connectorCards/MetaMaskCard.tsx
  src/connectors/gnosisSafe.ts
  src/containers/Analytics/ContractsTable.tsx
  src/containers/Analytics/DataCard.tsx
  src/containers/Analytics/DataTable.tsx
  src/containers/Analytics/index.tsx
  src/containers/Auctions/CollateralAuctions/CollateralAuctionBlock.tsx
  src/containers/Shared.tsx
  src/containers/Vaults/CreateVault.tsx
  src/containers/Vaults/ModifyVault.tsx
  src/containers/Vaults/Stats.js
  src/containers/Vaults/VaultDetails.tsx
  src/containers/Vaults/VaultHeader.tsx
  src/containers/Vaults/index.tsx
  src/hooks/useActiveWeb3React.ts
  src/hooks/useTokenApproval.tsx
  src/index.tsx
  src/services/TransactionUpdater.tsx
  src/utils/formatDataNumber.ts
  src/utils/helper.ts
  src/utils/helpers.js
Labels: web, dependency change, size/L

#307 Issue #287: Update Header to New Design
  src/assets/od-wallet-icon.svg
  src/assets/parachute-icon.svg
  src/assets/wallet-icon.svg
  src/components/NavLinks.tsx
  src/components/Navbar.tsx
  src/components/SideMenu.tsx
Labels: web

#305 Issue #304: Fix Styled Components not Inheriting React Props
  package.json
  src/components/Slider.tsx
  src/connectors/NetworkConnector.ts
  src/containers/Analytics/DataCard.tsx
  src/containers/Vaults/VaultDetails.tsx
  src/hooks/useGeb.ts
  tsconfig.json
  yarn.lock
Labels: web, dependency change, size/L

#310 Issue #308: Debt owed, input owed amount
  src/components/VaultStats.tsx
  src/hooks/useGeb.ts
Labels: web, dependency change, size/S

#318 Add new bot URL
  src/services/checkSanctions.ts
Labels: web

#317 Issue #311: OD-1 CSP Configuration (od-app PR)
  public/index.html
  public/tracking.js
Labels: size/M
