Repository open-dollar/od-app, pull requests merged in 2024-02, with the labels that each got.

#246 Chore: Run ESLint and Prettier
  package.json
  src/App.tsx
  src/components/CookieBanner.tsx
  src/components/Footer.tsx
  src/containers/Shared.tsx
  src/containers/Vaults/CreateVault.tsx
  src/containers/Vaults/Stats.js
  src/hooks/useTokenApproval.tsx
Labels: web, dependency change, size/L

#250 Deployment 02-02-2024
  package.json
  yarn.lock
Labels: dependency change, size/S

#245 Issue #244: Deposit TVL Flow
  src/App.tsx
  src/components/Slider.tsx
  src/containers/Deposit/DepositFunds.tsx
  src/hooks/useGeb.ts
  src/utils/helper.ts
  src/utils/i18n/en.json
Labels: web, dependency change, size/XL

#249 Issue #248: Prep app for TVL
  src/App.tsx
  src/components/NavLinks.tsx
  src/components/Navbar.tsx
  src/components/Steps.tsx
  src/containers/Deposit/index.tsx
  src/containers/Vaults/index.tsx
  src/model/safeModel.ts
  src/utils/i18n/en.json
Labels: web, dependency change, size/M

#254 Issue #238: Add Deposit Page
  src/components/Footer.tsx
  src/components/NavLinks.tsx
  src/components/Navbar.tsx
  src/containers/Deposit/DepositDetails.tsx
  src/containers/Deposit/index.tsx
  src/containers/Vaults/Stats.js
  src/model/safeModel.ts
  src/utils/i18n/en.json
Labels: web, size/L

#256 Issue #239: View Deposit Asset List
  src/components/Deposit/DepositBlock.tsx
  src/containers/Deposit/DepositDetails.tsx
  src/containers/Deposit/DepositFunds.tsx
  src/containers/Deposit/index.tsx
  src/hooks/index.ts
  src/hooks/useNitroPool.ts
  src/model/depositModel.ts
  src/model/index.ts
  src/utils/helper.ts
  src/utils/i18n/en.json
Labels: web, size/L

#257 Issue #240: Display Pool Details
  src/components/Deposit/DepositBlock.tsx
  src/components/Deposit/DepositDetailsCard.tsx
  src/components/Deposit/index.tsx
  src/components/StatusPill.tsx
  src/containers/Deposit/DepositDetails.tsx
  src/containers/Deposit/DepositFunds.tsx
  src/containers/Deposit/index.tsx
  src/hooks/useNitroPool.ts
  src/model/depositModel.ts
  src/types/deposits.ts
  src/types/index.ts
  src/utils/constants.ts
  src/utils/helper.ts
  src/utils/i18n/en.json
Labels: web, size/XL

#260 Issue #247: Restrict Leading Zeros in TokenInput
  src/components/TokenInput.tsx
  src/containers/Vaults/Stats.js
Labels: web, size/M

#259 Issue #251: Review dependabot alerts
  package.json
  tsconfig.json
  yarn.lock
Labels: dependency change, size/XXL

#262 Issue #261: Disable withdrawing all collateral from vault
  src/utils/helper.ts
Labels: web
