Repository open-dollar/od-app, pull requests merged in 2024-04, with the labels that each got.

#325 Issue #314: OD-4 wstETH price
  public/tracking.js
  src/components/VaultStats.tsx
  src/containers/Vaults/ModifyVault.tsx
  src/hooks/useGeb.ts
Labels: web, size/M

#332 Remove deprecated check
  src/index.tsx
Labels: web, size/XS

#279 Enable Optimism HAI
  README.md
  package.json
  public/index.html
  src/chains.ts
  src/components/WalletModal/index.tsx
  src/hooks/useGeb.ts
  src/utils/chains.ts
  src/utils/constants.ts
  src/utils/interfaces.ts
  yarn.lock
Labels: web, dependency change, size/L

#340 Prevent Network Errors on switch chain
  src/chains.ts
  src/components/Navbar.tsx
  src/components/SideMenu.tsx
  src/components/WalletModal/index.tsx
  src/containers/Shared.tsx
  src/containers/Vaults/Stats.js
  src/containers/Vaults/index.tsx
  src/hooks/useGeb.ts
  src/utils/auctions.ts
  src/utils/constants.ts
  src/utils/wrapEther.ts
Labels: web, ch-32, size/L

#337 Issue #330: Always show interactive element for vaults
  src/containers/Vaults/VaultDetails.tsx
  src/utils/i18n/en.json
Labels: web, dependency change, size/XS

#342 Issue #294: App Redesign: new footer
  src/components/Footer.tsx
Labels: web, size/L

#348 Issue #316. App Redesign: Cookie Consent Banner
  src/components/CookieBanner.tsx
  src/components/Footer.tsx
Labels: web, ch-33, size/M

#328 App Redesign: new hero section (no vaults)
  src/assets/check.svg
  src/assets/closed-vault.png
  src/assets/facilitator.png
  src/assets/opened-vault.png
  src/assets/vault-facilitator.png
  src/assets/wallet.png
  src/components/Button.tsx
  src/components/Icons/Check.tsx
  src/components/Stepper.tsx
  src/components/Steps.tsx
  src/components/StepsContent.tsx
  src/containers/Vaults/Accounts.tsx
  src/utils/i18n/en.json
  src/utils/interfaces.ts
  src/utils/themes/dark.ts
Labels: web, ch-32, size/L

#355 set up state for bridge
  src/components/Modals/BridgeModal.tsx
  src/components/NavLinks.tsx
  src/containers/Bridge/BridgeFundsForm.tsx
  src/containers/Bridge/index.tsx
  src/containers/Shared.tsx
  src/model/bridgeModel.ts
  src/model/index.ts
  src/utils/formatBridgeUrl.ts
  src/utils/interfaces.ts
Labels: web, size/L

#360 4-9-24 deployment
  package.json
  yarn.lock
Labels: dependency change, size/M

#357 Issue #288: open graph image
  public/index.html
  public/manifest.json
  public/og.png
Labels: web, dependency change, size/S

#364 Issue #346: App Redesign: Account Modal
  src/components/ConnectedWalletInfo.tsx
  src/components/Icons/CopyIcon.tsx
  src/components/Icons/Identicon.tsx
  src/components/Modals/ConnectedWalletModal.tsx
  src/components/Modals/Modal.tsx
  src/components/Modals/SafeManagerModal.tsx
  src/components/Transaction.tsx
  src/components/VaultManager.tsx
Labels: web, size/L

#356 Issue #293. App Redesign: stats component on modify vaults page
  src/App.tsx
  src/assets/stats-img-lock.png
  src/assets/stats-img-vault.png
  src/containers/Analytics/ContractsTable.tsx
  src/containers/Analytics/DataCard.tsx
  src/containers/Analytics/DataTable.tsx
  src/containers/Analytics/index.tsx
  src/utils/themes/light.ts
Labels: web, ch-33, size/L

#370 Redesign Header and Side Menu
  src/components/Modals/ConnectedWalletModal.tsx
  src/components/Modals/WaitingModal.tsx
  src/components/NavLinks.tsx
  src/components/Navbar.tsx
  src/components/SideMenu.tsx
Labels: web, size/M

#365 fix route & state
  src/components/Steps.tsx
  src/containers/Shared.tsx
Labels: web, size/M

#361 Issue 297. App Redesign: Create vault page
  src/assets/wsteth.svg
  src/components/Button.tsx
  src/components/Dropdown.tsx
  src/components/TokenInput.tsx
  src/containers/Vaults/CreateVault.tsx
  src/utils/themes/light.ts
  src/utils/tokens.ts
Labels: web, ch-33, size/L

#378 button
  src/components/AuctionBlock.tsx
  src/components/AuctionsFAQ.tsx
  src/components/AuctionsOperations/AuctionsPayment.tsx
  src/components/BidLine.tsx
  src/components/Button.tsx
  src/components/ConnectedWalletInfo.tsx
  src/components/DecimalInput.tsx
  src/components/Modals/ProxyModal.tsx
  src/components/Navbar.tsx
  src/components/NotificationPopup.tsx
  src/components/SideMenu.tsx
  src/components/ToastPayload.tsx
  src/components/VaultManager.tsx
  src/containers/Analytics/DataCard.tsx
  src/containers/Auctions/CollateralAuctions/CollateralAuctionBlock.tsx
  src/containers/Vaults/wrapEth/Wrap.tsx
  src/utils/constants.ts
  src/utils/interfaces.ts
Labels: web, size/L

#372 Issue 292. App Redesign: new hero section (w/vault list)
  src/components/CheckBox.tsx
  src/components/VaultBlock.tsx
  src/containers/Vaults/CreateVault.tsx
  src/containers/Vaults/VaultList.tsx
  src/index.css
  src/utils/interfaces.ts
  src/utils/themes/shared.ts
Labels: web, ch-33, size/L

#374 Issue #300. App Redesign: Auctions page
  src/components/AuctionsFAQ.tsx
  src/containers/Auctions/AuctionsList.tsx
  src/containers/Auctions/CollateralAuctions/CollateralAuctionsList.tsx
  src/containers/Auctions/index.tsx
  src/containers/Vaults/CreateVault.tsx
  src/containers/Vaults/VaultList.tsx
Labels: web, ch-33, size/L

#377 Issue #299: App Redesign: Lower part of modify vault page
  src/components/Button.tsx
  src/components/LinkButton.tsx
  src/components/TokenInput.tsx
  src/containers/Analytics/DataCard.tsx
  src/containers/Vaults/ModifyVault.tsx
Labels: web, size/L

#373 Issue #345: Cleanup onboarding
  src/components/Button.tsx
  src/components/Stepper.tsx
  src/components/Steps.tsx
  src/components/StepsContent.tsx
  src/containers/Shared.tsx
  src/utils/i18n/en.json
Labels: web, size/M

#379 Issue #298: App Redesign: Upper part of modify vault page
  src/components/VaultStats.tsx
  src/containers/Vaults/VaultDetails.tsx
  src/containers/Vaults/VaultHeader.tsx
Labels: web, size/L

#380 Fix UI bugs, wallet not connecting on first load, type issues, and styles
  src/components/AccountCardsWeb3ReactV2.tsx
  src/components/Button.tsx
  src/components/Loader.tsx
  src/components/connectorCards/MetaMaskCard.tsx
  src/components/connectorCards/WalletConnectV2Card.tsx
  src/containers/Vaults/CreateVault.tsx
  src/containers/Vaults/ModifyVault.tsx
  src/hooks/useActiveWeb3React.ts
Labels: web, size/L

#388 Remove gh-pages
  package.json
  yarn.lock
Labels: dependency change, size/L

#385 QA 2 - loaders spinners & button
  src/components/Loader.tsx
  src/components/Modals/WaitingModal.tsx
Labels: web, size/XS

#386 Issue 383. QA - Web Redesign: (part 3)
  src/components/CookieBanner.tsx
  src/components/Footer.tsx
  src/components/NavLinks.tsx
  src/components/WalletModal/index.tsx
  src/containers/Analytics/ContractsTable.tsx
  src/containers/Analytics/DataTable.tsx
  src/containers/Analytics/index.tsx
  src/containers/Vaults/CreateVault.tsx
  src/containers/Vaults/VaultDetails.tsx
  src/containers/Vaults/VaultList.tsx
Labels: web, ch-34, size/L

#391 Remove Unused Dependencies
  package.json
  src/utils/index.test.ts
  yarn.lock
Labels: web, dependency change, ch-34, size/L

#395 Issue 394. App Redesign: Background Image
  public/squares1x.png
  public/wavy-blue.png
  src/GlobalStyle.tsx
Labels: web, ch-34, size/XS

#396 Issue #366: Shared Store State
  src/containers/Shared.tsx
  src/hooks/useAllowanceCheck.ts
  src/hooks/useAuctionDataUpdate.ts
  src/hooks/useCoinBalanceUpdate.ts
  src/hooks/useSafeData.ts
  src/hooks/useTokenData.ts
  src/model/safeModel.ts
Labels: web, size/L

#399 Add maintenance middleware
  package.json
  src/App.tsx
  src/GlobalStyle.tsx
  src/components/AuctionBlock.tsx
  src/components/BidLine.tsx
  src/components/NavLinks.tsx
  src/components/Navbar.tsx
  src/components/Slider.tsx
  src/containers/Analytics/DataTable.tsx
  src/containers/Auctions/CollateralAuctions/CollateralAuctionBlock.tsx
  src/containers/Deposit/DepositFunds.tsx
  src/containers/Maintenance.tsx
  src/containers/MaintenanceRedirect.tsx
  src/containers/Shared.tsx
  yarn.lock
Labels: web, dependency change, size/L

#402 Issue #400: Add redesign: geofence
  public/index.html
Labels: size/XS

#405 Disable liquidity button temporarily in navbar
  src/components/Navbar.tsx
Labels: web, size/S

#415 Issue #413: Approval not working for Deposit and Repay on ModifyVault
  src/containers/Vaults/ModifyVault.tsx
Labels: web, size/M

#416 Issue #407. QA: Header, test tokens
  src/components/Navbar.tsx
  src/components/Steps.tsx
  src/containers/Analytics/ContractsTable.tsx
  src/containers/Vaults/index.tsx
Labels: web, ch-34, size/M

#418 Add more countries to geoblock
  src/containers/Shared.tsx
Labels: web, size/XS

#425 Fix repay all debt
  src/services/blockchain.ts
Labels: web, size/XS

#417 Add back camelot pool in header
  package.json
  src/components/Navbar.tsx
  yarn.lock
Labels: web, dependency change, size/M

#422 Sentry Monitoring
  .gitignore
  craco.config.js
  package.json
  public/index.html
  src/App.tsx
  src/components/Navbar.tsx
  yarn.lock
Labels: web, dependency change, ch-34, size/XXL, post-launch

#429 Issue #406. QA: Side menu
  src/components/NavLinks.tsx
  src/components/SideMenu.tsx
Labels: web, ch-34, size/L

#432 Create account if no facilitator, Error handling, precision
  .gitignore
  src/components/Button.tsx
  src/components/ConnectWalletStep.tsx
  src/containers/Analytics/index.tsx
  src/containers/Vaults/CreateVault.tsx
  src/hooks/TransactionHooks.tsx
  src/hooks/useSafe.ts
Labels: web, size/L

#434 Issue #414. QA: Image Loading and container
  src/assets/stats-img-lock.png
  src/assets/stats-img-lock.webp
  src/assets/stats-img-vault.png
  src/assets/stats-img-vault.webp
  src/containers/Analytics/DataCard.tsx
  src/containers/Analytics/index.tsx
  src/containers/Auctions/index.tsx
Labels: web, ch-34, size/M
