Repository open-dollar/od-app, pull requests merged in 2024-05, with the labels that each got.

#435 Issue #430. Stake: UI active pools
  src/App.tsx
  src/components/NavLinks.tsx
  src/containers/Earn/PoolBlock.js
  src/containers/Earn/index.tsx
  src/utils/i18n/en.json
Labels: web, ch-34, size/L

#439 Issue #437. Geoblock updates - separate page
  src/App.tsx
  src/components/BlockBodyContainer.tsx
  src/components/Navbar.tsx
  src/containers/GeoBlockContainer.tsx
  src/containers/Shared.tsx
Labels: web, dependency change, size/L

#442 Basic actions, svg renderer
  package.json
  src/components/VaultStats.tsx
  src/utils/gebManager/index.ts
  yarn.lock
Labels: web, dependency change, size/M

#443 v1.7.0 release
  README.md
  package.json
  src/components/VaultStats.tsx
  src/utils/gebManager/index.ts
  yarn.lock
Labels: web, dependency change, size/M

#448 Improve error reporting
  package.json
  public/index.html
  src/App.tsx
  src/chains.ts
  src/containers/Vaults/ModifyVault.tsx
  tsconfig.json
  yarn.lock
Labels: web, dependency change, size/L

#452 Issue #446: Display stats collateraljoin contracts
  src/containers/Analytics/index.tsx
Labels: web, size/S

#453 Issue #445: Repay for vault you don't own
  src/components/LinkButton.tsx
  src/containers/Vaults/ModifyVault.tsx
  src/containers/Vaults/VaultDetails.tsx
Labels: web, size/S

#454 Remove 5% Buffer On Vault Creation with Max Balance
  src/containers/Vaults/CreateVault.tsx
Labels: web, ch-35

#468 Issue #462: Vault creation decimals
  src/hooks/useSafe.ts
Labels: web, size/XS

#458 Issue #447. Show NFV Owner
  src/components/VaultStats.tsx
Labels: web, size/M, ch-35

#469 Issue #450. Footer column alignment
  src/components/Footer.tsx
Labels: web, size/S, ch-35

#467 Issue #466: RETH deposit bug
  Earthfile
  src/containers/Vaults/CreateVault.tsx
  src/containers/Vaults/ModifyVault.tsx
  src/hooks/useCollateralBalances.ts
  src/hooks/useSafe.ts
  src/utils/helper.ts
Labels: web, size/L

#472 Issue #461: Wallet modal improvements
  src/components/ConnectedWalletInfo.tsx
  src/components/Modals/ConnectedWalletModal.tsx
  src/components/Modals/WaitingModal.tsx
  src/components/ToastPayload.tsx
  src/components/Transaction.tsx
  src/utils/i18n/en.json
Labels: web, size/L

#478 liquidation penalty price
  src/hooks/useSafe.ts
Labels: web, size/S

#481 Issue #473: CORS errors
  public/index.html
Labels: size/XS

#476 Issue #460: Wallet connection improvements
  src/App.tsx
  src/GlobalStyle.tsx
  src/components/AccountCardsWeb3ReactV2.tsx
  src/components/ConnectWithSelect.tsx
  src/components/ConnectedWalletInfo.tsx
  src/components/Modals/Modal.tsx
  src/components/connectorCards/Card.tsx
  src/components/connectorCards/CoinbaseWalletCard.tsx
  src/components/connectorCards/GnosisCard.tsx
  src/components/connectorCards/MetaMaskCard.tsx
  src/components/connectorCards/Status.tsx
  src/components/connectorCards/WalletConnectV2Card.tsx
  src/model/popupsModel.ts
  src/model/settingsModel.test.ts
  src/model/settingsModel.ts
  src/utils/i18n/en.json
Labels: web, size/L

#436 Fetch nitro pools state
  package.json
  public/index.html
  src/assets/unknown-token.svg
  src/components/NavLinks.tsx
  src/containers/Earn/PoolBlock.tsx
  src/containers/Earn/index.tsx
  src/model/index.ts
  src/model/nitroPoolsModel.ts
  src/utils/interfaces.ts
  src/utils/tokens.ts
  yarn.lock
Labels: web, dependency change, size/L

#479 bridge UI
  src/components/Modals/BridgeModal.tsx
  src/components/Steps.tsx
  src/containers/Bridge/BridgeFundsForm.tsx
  src/containers/Bridge/index.tsx
  src/model/bridgeModel.ts
  src/utils/chains.ts
  src/utils/formatBridgeUrl.ts
  src/utils/interfaces.ts
  src/utils/tokens.ts
Labels: web, size/L

#493 Issue #491. APY tooltip
  src/containers/Earn/PoolBlock.tsx
Labels: web, size/S, ch-35

#490 Issue #486. Earn page improvements
  package.json
  public/index.html
  src/containers/Earn/EarnDetails.tsx
  src/containers/Earn/PoolBlock.tsx
  src/containers/Earn/index.tsx
  src/model/nitroPoolsModel.ts
  src/utils/constants.ts
  src/utils/interfaces.ts
  yarn.lock
Labels: web, dependency change, size/XXL, ch-35

#485 Issue #474. Header QA
  src/components/NavLinks.tsx
  src/components/Navbar.tsx
Labels: web, size/S, ch-35

#482 fuul sdk set up
  package.json
  public/index.html
  src/App.tsx
  src/components/Steps.tsx
  src/containers/Affiliate/index.tsx
  src/containers/Shared.tsx
  src/hooks/useFuulSDK.ts
  yarn.lock
Labels: web, dependency change, size/L

#520 Release - fuul error handling
  public/index.html
  public/manifest.json
  src/App.tsx
  src/components/VaultStats.tsx
Labels: web, size/M

#521 Bolts page
  src/App.tsx
  src/ErrorBoundary.tsx
  src/assets/camelot.svg
  src/assets/cbETH.svg
  src/assets/check.svg
  src/assets/connectors/metamask-fox.svg
  src/assets/galxe.svg
  src/assets/nfts-icon.svg
  src/assets/parachute-icon.svg
  src/assets/unknown-token.svg
  src/assets/zealy.svg
  src/components/ApproveToken.tsx
  src/components/Icons/Check.tsx
  src/components/Icons/Metamask.tsx
  src/components/Modals/ProxyModal.tsx
  src/components/Modals/WaitingModal.tsx
  src/components/NavLinks.tsx
  src/containers/Bolts/Affiliate.tsx
  src/containers/Bolts/QuestBlock.tsx
  src/containers/Bolts/index.tsx
  src/containers/Bolts/quests.tsx
  src/hooks/useFuulSDK.ts
Labels: web, size/XXL

#518 Marketplace: Data Fetching
  public/index.html
  src/App.tsx
  src/containers/Marketplace/index.tsx
  src/hooks/useOpenSeaListings.ts
  src/services/opensea.ts
Labels: web, size/L

#513 Fetch Collateral Balances for Bridge table
  public/index.html
  src/containers/Bridge/BridgeFundsForm.tsx
  src/containers/Vaults/CreateVault.tsx
  src/utils/chains.ts
  src/utils/tokens.ts
Labels: web, size/L

#514 Issue #503. Bridge: Main interaction component.
  src/containers/Bridge/BridgeFundsForm.tsx
  src/containers/Bridge/index.tsx
Labels: web, size/L, ch-36

#529 Botls page leanup
  src/containers/Bolts/Affiliate.tsx
  src/containers/Bolts/QuestBlock.tsx
  src/containers/Bolts/index.tsx
  src/containers/Bolts/quests.tsx
  src/containers/Earn/index.tsx
Labels: web, size/L

#527 Issue #510. Marketplace: NFV Listing Card
  package.json
  public/index.html
  src/containers/Analytics/index.tsx
  src/containers/Earn/index.tsx
  src/containers/Marketplace/Table.tsx
  src/containers/Marketplace/index.css
  src/containers/Marketplace/index.tsx
  src/containers/Vaults/VaultDetails.tsx
  src/hooks/useOpenSeaListings.ts
  src/hooks/useVaultSubgraph.ts
  src/services/opensea.ts
  src/utils/datesAndTimes.ts
  src/utils/interfaces.ts
  src/utils/themes/light.ts
  yarn.lock
Labels: web, dependency change, ch-36, size/XL

#540 Issue #504. Bridge: Table interaction
  src/containers/Bridge/BridgeFundsForm.tsx
  src/containers/Vaults/CreateVault.tsx
  src/containers/Vaults/ModifyVault.tsx
  src/model/bridgeModel.ts
  src/utils/formatBridgeUrl.ts
  src/utils/tokens.ts
Labels: web, size/L, ch-36

#546 Issue #507. Bridge: low gas improvements
  src/components/Modals/LowGasModal.tsx
  src/components/Steps.tsx
  src/containers/Shared.tsx
  src/model/popupsModel.ts
  src/utils/tokens.ts
Labels: web, size/L, ch-36
