Repository open-dollar/od-app, pull requests merged in 2024-07, with the labels that each got.

#581 Earn page react-loading-skeleton
  src/App.tsx
  src/containers/Earn/PoolBlock.tsx
  src/containers/Earn/index.tsx
  yarn.lock
Labels: web, size/XXL, ch-38

#603 Issue #549: App Speed
  public/index.html
  public/squares1x.png
  public/squares1x.webp
  public/wavy-blue.png
  public/wavy-blue.webp
  src/App.tsx
  src/GlobalStyle.tsx
  src/assets/closed-vault.webp
  src/components/CookieBanner.tsx
  src/components/StepsContent.tsx
  src/containers/Shared.tsx
  src/utils/tokens.ts
Labels: web, size/L

#608 Issue #607: Add global vault state
  src/hooks/useSafeData.ts
  src/model/globalSafeModel.ts
  src/model/index.ts
  src/services/safes.ts
  src/utils/gebManager/index.ts
  src/utils/helper.ts
  src/utils/interfaces.ts
Labels: web, size/L

#604 Bolts multiplier update
  public/index.html
  src/chains.ts
  src/components/Bolts/AddressCell.tsx
  src/containers/Bolts/Leaderboard.tsx
  src/containers/Bolts/index.tsx
  src/containers/Bolts/quests.tsx
  src/model/boltsModel.ts
  src/services/checkSanctions.ts
Labels: web, size/L

#613 Issue #612: matomo race conditions
  public/index.html
Labels: web, size/XS

#618 Typo fix
  src/containers/Analytics/index.tsx
Labels: web, size/XS

#611 Issue #606: Vaults explorer page
  src/App.tsx
  src/containers/Explore/ExploreTable.tsx
  src/containers/Explore/index.css
  src/containers/Explore/index.tsx
  src/hooks/useVaultSubgraph.ts
  src/utils/helper.ts
Labels: web, size/XL

#620 Update bolts program
  package.json
  src/App.tsx
  src/components/Steps.tsx
  src/containers/Bolts/Affiliate.tsx
  src/hooks/useFuulSDK.ts
  yarn.lock
Labels: web, dependency change, size/L

#621 Add WETH
  package.json
  yarn.lock
Labels: dependency change, size/S

#622 add credit guild block
  src/containers/Earn/EarnBlock.tsx
  src/containers/Earn/index.tsx
Labels: web, size/L

#623 Od-weth QA
  src/components/VaultStats.tsx
  src/model/boltsModel.ts
  src/services/checkSanctions.ts
  src/utils/constants.ts
  src/utils/gebManager/index.ts
Labels: web, size/M

#609 New "initializing" loader
  src/components/Modals/WaitingModal.tsx
  src/components/Steps.tsx
  src/containers/Shared.tsx
  src/containers/Vaults/index.tsx
  src/model/safeModel.ts
Labels: web, dependency change, size/L, ch-39

#628 WETH collateral release
  package.json
  public/index.html
  src/App.tsx
  src/components/Modals/WaitingModal.tsx
  src/components/Steps.tsx
  src/components/VaultStats.tsx
  src/containers/Analytics/index.tsx
  src/containers/Bolts/Affiliate.tsx
  src/containers/Bolts/index.tsx
  src/containers/Earn/EarnBlock.tsx
  src/containers/Earn/index.tsx
  src/containers/Explore/ExploreTable.tsx
  src/containers/Explore/index.css
  src/containers/Explore/index.tsx
  src/containers/Shared.tsx
  src/containers/Vaults/index.tsx
  src/hooks/useFuulSDK.ts
  src/hooks/useVaultSubgraph.ts
  src/model/boltsModel.ts
  src/model/safeModel.ts
  src/services/checkSanctions.ts
  src/utils/constants.ts
  src/utils/gebManager/index.ts
  src/utils/helper.ts
  yarn.lock
Labels: web, dependency change, size/XXL

#631 Borrow + Deposit tabs cleanup
  src/components/LinkButton.tsx
  src/containers/Earn/EarnBlock.tsx
  src/containers/Vaults/ModifyVault.tsx
Labels: web, size/M, ch-39

#632 Address ENS loading skeleton
  src/components/Navbar.tsx
  src/components/SideMenu.tsx
  src/components/VaultStats.tsx
  src/containers/Earn/index.tsx
Labels: web, size/M

#602 Update react, react-router
  package.json
  src/App.tsx
  src/components/Analytics/GoogleTagManager.tsx
  src/components/Modals/LiquidateSafeModal.tsx
  src/components/NavLinks.tsx
  src/components/Steps.tsx
  src/components/VaultBlock.tsx
  src/components/VaultManager.tsx
  src/containers/Auctions/index.tsx
  src/containers/Bolts/quests.tsx
  src/containers/Bridge/LiFiWidget.tsx
  src/containers/Deposit/DepositFunds.tsx
  src/containers/Earn/EarnDetails.tsx
  src/containers/Shared.tsx
  src/containers/Splash.tsx
  src/containers/Vaults/CreateVault.tsx
  src/containers/Vaults/ModifyVault.tsx
  src/containers/Vaults/VaultDetails.tsx
  src/containers/Vaults/VaultHeader.tsx
  src/containers/Vaults/index.tsx
  src/index.tsx
  src/utils/formatBridgeUrl.ts
  yarn.lock
Labels: web, dependency change

#633 Issue #557: View internal balances
  package.json
  src/components/VaultBlock.tsx
  src/components/VaultStats.tsx
  src/utils/i18n/en.json
  yarn.lock
Labels: web, dependency change, size/M

#639 Issue #630: Explore page design improvements
  src/containers/Explore/ExploreTable.tsx
  src/containers/Explore/index.tsx
  src/utils/generateSVGRing.ts
  src/utils/helper.ts
Labels: web, size/L

#643 Fix useHistory issue in dev deployment
  src/containers/Explore/ExploreTable.tsx
Labels: web

#652 Add GRT
  package.json
  public/index.html
  src/assets/grt.svg
  src/chains.ts
  src/containers/Vaults/CreateVault.tsx
  src/containers/Vaults/ModifyVault.tsx
  src/utils/tokens.ts
  yarn.lock
Labels: web, dependency change, size/L

#649 Bump svg generator package
  package.json
  yarn.lock
Labels: dependency change, size/S

#653 Release: Add GRT collateral
  package.json
  public/index.html
  src/App.tsx
  src/assets/grt.svg
  src/chains.ts
  src/components/Analytics/GoogleTagManager.tsx
  src/components/CreateVaultStep.tsx
  src/components/LinkButton.tsx
  src/components/Modals/LiquidateSafeModal.tsx
  src/components/NavLinks.tsx
  src/components/Navbar.tsx
  src/components/SideMenu.tsx
  src/components/Steps.tsx
  src/components/VaultBlock.tsx
  src/components/VaultManager.tsx
  src/components/VaultStats.tsx
  src/components/connectorCards/WalletConnectV2Card.tsx
  src/containers/Auctions/index.tsx
  src/containers/Bolts/quests.tsx
  src/containers/Bridge/LiFiWidget.tsx
  src/containers/Deposit/DepositFunds.tsx
  src/containers/Earn/EarnBlock.tsx
  src/containers/Earn/EarnDetails.tsx
  src/containers/Earn/index.tsx
  src/containers/Explore/ExploreTable.tsx
  src/containers/Explore/index.tsx
  src/containers/Shared.tsx
  src/containers/Splash.tsx
  src/containers/Vaults/CreateVault.tsx
  src/containers/Vaults/ModifyVault.tsx
  src/containers/Vaults/VaultDetails.tsx
  src/containers/Vaults/VaultHeader.tsx
  src/containers/Vaults/index.tsx
  src/hooks/useActiveWeb3React.ts
  src/index.tsx
  src/utils/formatBridgeUrl.ts
  src/utils/generateSVGRing.ts
  src/utils/helper.ts
  src/utils/i18n/en.json
  src/utils/tokens.ts
  yarn.lock
Labels: web, dependency change, size/XXL

#638 Replace all 'any' with correct Types
  src/GlobalStyle.tsx
  src/components/AccountCardsWeb3ReactV2.tsx
  src/components/ApproveToken.tsx
  src/components/AuctionBlock.tsx
  src/components/BidLine.tsx
  src/components/Bolts/AddressCell.tsx
  src/components/Dropdown.tsx
  src/components/LinkButton.tsx
  src/components/Modals/WaitingModal.tsx
  src/components/NavLinks.tsx
  src/components/Navbar.tsx
  src/components/NotificationPopup.tsx
  src/components/Slider.tsx
  src/components/WalletModal/Option.tsx
  src/components/connectorCards/Card.tsx
  src/containers/Analytics/DataTable.tsx
  src/containers/Auctions/CollateralAuctions/CollateralAuctionBlock.tsx
  src/containers/Bolts/Leaderboard.tsx
  src/containers/Bolts/QuestBlock.tsx
  src/containers/Deposit/DepositFunds.tsx
  src/containers/Earn/PoolBlock.tsx
  src/containers/Earn/index.tsx
  src/containers/GeoBlockContainer.tsx
  src/containers/Vaults/ModifyVault.tsx
  src/utils/retry.ts
Labels: web, size/L, ch-40

#657 App meta tags
  package.json
  src/GlobalStyle.tsx
  src/components/MetaTags.tsx
  src/containers/Analytics/index.tsx
  src/containers/Auctions/index.tsx
  src/containers/Bolts/index.tsx
  src/containers/Bridge/index.tsx
  src/containers/Earn/index.tsx
  src/containers/Vaults/VaultList.tsx
  src/containers/Vaults/index.tsx
  src/utils/metaInfo.ts
  yarn.lock
Labels: web, dependency change, ch-40, size/XL

#660 Issue #656 (app PR): country.is failure
  src/containers/Shared.tsx
  src/services/checkGeoBlockAndSanctions.ts
Labels: web, size/M

#661 Add PT-rETH PT-wstETH
  package.json
  src/assets/gm-eth.svg
  src/assets/grt.svg
  src/assets/pendle-pt-reth.svg
  src/assets/pendle-pt-wsteth.svg
  src/utils/tokens.ts
  yarn.lock
Labels: web, dependency change, size/L

#646 QA: Header
  src/components/NavLinks.tsx
  src/components/Navbar.tsx
  src/components/SideMenu.tsx
Labels: web, size/M, ch-40

#664 Issue #663: Fix Gnosis Safe in app
  src/components/ConnectedWalletInfo.tsx
  src/components/Navbar.tsx
  src/components/SideMenu.tsx
  src/components/Web3ReactManager/index.tsx
Labels: web, size/M

#666 PT Assets
  package.json
  public/index.html
  src/GlobalStyle.tsx
  src/assets/gm-eth.svg
  src/assets/grt.svg
  src/assets/pendle-pt-reth.svg
  src/assets/pendle-pt-wsteth.svg
  src/components/AccountCardsWeb3ReactV2.tsx
  src/components/ApproveToken.tsx
  src/components/AuctionBlock.tsx
  src/components/BidLine.tsx
  src/components/Bolts/AddressCell.tsx
  src/components/ConnectedWalletInfo.tsx
  src/components/Dropdown.tsx
  src/components/LinkButton.tsx
  src/components/MetaTags.tsx
  src/components/Modals/WaitingModal.tsx
  src/components/NavLinks.tsx
  src/components/Navbar.tsx
  src/components/NotificationPopup.tsx
  src/components/SideMenu.tsx
  src/components/Slider.tsx
  src/components/WalletModal/Option.tsx
  src/components/Web3ReactManager/index.tsx
  src/components/connectorCards/Card.tsx
  src/containers/Analytics/DataTable.tsx
  src/containers/Analytics/index.tsx
  src/containers/Auctions/CollateralAuctions/CollateralAuctionBlock.tsx
  src/containers/Auctions/index.tsx
  src/containers/Bolts/Leaderboard.tsx
  src/containers/Bolts/QuestBlock.tsx
  src/containers/Bolts/index.tsx
  src/containers/Bridge/index.tsx
  src/containers/Deposit/DepositFunds.tsx
  src/containers/Earn/PoolBlock.tsx
  src/containers/Earn/index.tsx
  src/containers/GeoBlockContainer.tsx
  src/containers/Shared.tsx
  src/containers/Vaults/ModifyVault.tsx
  src/containers/Vaults/VaultDetails.tsx
  src/containers/Vaults/VaultList.tsx
  src/containers/Vaults/index.tsx
  src/services/checkGeoBlockAndSanctions.ts
  src/utils/interfaces.ts
  src/utils/metaInfo.ts
  src/utils/retry.ts
  src/utils/themes/dark.ts
  src/utils/themes/light.ts
  src/utils/tokens.ts
  yarn.lock
Labels: web, dependency change, size/XXL
