Repository open-dollar/od-app, pull requests merged in 2024-01, with the labels that each got.

#223 Add github action
  .dockerignore
  .example.env
  .github/workflows/docker.yml
  .github/workflows/document-pr.yml
  Dockerfile
  README.md
  docker-compose.yml
  example.env
Labels: web, dependency change, size/L

#224 Issue #222: ODG icon, favicon
  src/assets/odg.svg
Labels: web, size/S

#227 1-16-deployment
  package.json
  src/containers/Vaults/VaultDetails.tsx
  yarn.lock
Labels: web, dependency change, size/M

#230 Fix od-logo.svg favicon
  public/od-logo.svg
Labels: size/S

#233 Fix TOS and privacy policy links
  src/components/Footer.tsx
Labels: web

#235 update text
  src/containers/Vaults/ModifyVault.tsx
Labels: web, size/XS

#226 Docker image optimizaion
  .github/workflows/docker.yml
  Dockerfile
  README.md
  docker-compose.yml
  example.env
Labels: web, dependency change, size/M

#242 Deployment 01-26-2024
  package.json
  yarn.lock
Labels: dependency change, size/S

#243 Issue #237: Display collateral balances
  src/components/Dropdown.tsx
  src/containers/Vaults/CreateVault.tsx
Labels: web, size/M
